---
title: "Data Types"
author: "Janos Strasszer"
date: "October 7, 2016"
output:
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Most important data types and corresponding operations in R

## Basic types
```{r basictypes}
# By default the type of number is double. It is called numeric sometimes.
typeof(12)
# For complex number the imaginary part is denoted by "i"
typeof(12+3i)
# A single character or any text : character
typeof("Some text")
# Logical variables can only two values: TRUE, FALSE or T, F as a short form
typeof(TRUE)
# Integers are mainly used as indexes
typeof(as.integer(12))
```

## Basic operations

### Numbers
```{r basicoperations}
# For numeric and integer all the mathematical operatons can be used
(1+2-3*4)/2
# Exp
5^2
# Square and n-th root
sqrt(25)
125^(1/3)
```

### Logical variables
```{r logicaloperations}
# AND : TRUE only if both of the values are TRUE
TRUE & TRUE
FALSE & TRUE
FALSE & FALSE
# OR : TRUE if at least one of the values are TRUE
TRUE | TRUE
FALSE | TRUE
FALSE | FALSE
```

### Text (Character)
```{r textoperations}
# concatanation of text (or numbers), the default separator is a space
paste("I have", 3, "apples.")
# Using empty separator
paste("I have", 3, "apples.", sep = "")
# Using custom separator
paste("I have", 3, "apples.", sep = " giggity ")
# Replacing parts of text with something
sub("3", "5", "I have 3 apples and 3 bananas.")
# Sub replaces only the first occurance. To have a "global" substitution use gsub
gsub("3", "5", "I have 3 apples and 3 bananas.")
```

## Vectors
```{r vectors}
# Vectors can be created with c(...)
x <- c(1, 2, 3, 4, 5) # Numeric vector
y <- c("a", "b", "c", "d", "e") # Character vector
z <- c(T, F, F, T, F) # Logical vector
# : can be used to create a range of integers
2:18 # Vector of integers from 2 to 18
2 * 1:9 # Vector of every second integer from 2 to 18
# COncatenate vectors
x321 <- c(x, c(3, 2, 1) )
print(x321)
```

## Creating DataFrames
```{r dataframes}
# Dataframes can be created with either loading a CSV file or by combining vectors
d <- data.frame(x, y, z, stringsAsFactors = FALSE) # We don't want the default option to create factors yet.
# R used the variable names as colum names
print(d, row.names=FALSE) # row.names=FALSE won't list row names/indexed
# Getting column names vector
colnames(d)
# Setting column names
colnames(d) <- c("First", "Second", "Third")
```

## Subsetting DataFrames
```{r subsetdataframes}
# TODO
```